[project]
name = "calibre-mcp"
version = "0.1.0"
description = "Calibre MCP Server to interact with a Calibre library via the Content Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.12.0",
]
